#!/usr/bin/env bash
export CONFIG_SERVICE_PASSWORD=111
export COMMUNICATION_SERVICE_PASSWORD=333
export MARKET_SERVICE_PASSWORD=444
export MONGODB_PASSWORD=222
export MONGO_INITDB_DATABASE=authdb

docker-compose up -d