FROM sebp/elkx

EXPOSE 5001

ADD /logstash/config/ /etc/logstash/conf.d/
#ADD /logstash/logstash.yml /out/logstash/config/logstash.yml
#ADD /logstash/logstash.yml /etc/logstash/logstash.yml
#ADD /logstash/logstash.yml /etc/logstash/config/logstash.yml
ADD /logstash/logstash.yml /opt/logstash/config/logstash.yml